---
title: "02c_TEM_to_SS_Raster"
author: "Matthew Coghill"
date: "2/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ls <- c("tidyverse", "raster", "caret")
bitbucket.packages <- c("rdsmart")
new.packages <- ls[!(ls %in% installed.packages()[, "Package"])]
new.bitbucket.packages <- bitbucket.packages[!bitbucket.packages %in% installed.packages()[, "Package"]]
if(length(new.packages))
  install.packages(new.packages)
if(length(new.bitbucket.packages))
  devtools::install_bitbucket("brendo1001/dsmart")
ls <- c(ls, bitbucket.packages)
lapply(ls, library, character.only = TRUE)
rm(ls, bitbucket.packages, new.packages, new.bitbucket.packages)
```

```{r define directories}
AOI <- "Sechelt"
AOI_dir <- file.path(paste0("./", AOI, "_AOI"))
map_res <- 4

shapes_path <- file.path(AOI_dir, "0_raw_inputs", "base_layers")
raster_path <- file.path(AOI_dir, "1_map_inputs", "covariates")

```


```{r extract raster values}
covariates <- list.files(file.path(raster_path, map_res), full.names = TRUE)

```

